package zadanie;

import zadanie.crypto.genalg.GeneticalAlgorithm;

/**
 *
 * @author vikto
 */
public class Zadanie {
    
    public static void main(String[] args) {

        //JDefault frame = new JDefault();

       GeneticalAlgorithm x = new GeneticalAlgorithm("HTHEEREAVEEBRNSEEVIALDADTTISONROPEETTPASNSCORNYIGLUNDITTHUEAEHOSRIEDSUEQLLNEOVPPERTECANSINAARTLEHNDETHOIGRHPEFISLEIQUFELTLMESRNURONTAEVLERHNDDANROOAKVHIOCUSEARTACMRSOFROTHTESERYVHARAPAPETEDOINAHELRPPCESSELECLIAEYTKINARBLELCSASMACOTDANTHACRAIERDOFHSNTEYAECRHAACTSERHRETINIEPLUBICDAOMMNIONSSEJIURODIICTDNSALEUINOGTONAHUTERIDSEIXTSENTONOSTHHETMYUOSDANTSEFSORHEACHSACRTEFSOOMEHTHEESEAVEEBRNCTONIOVSERHALCSURASEASPIEFSOLREEQUVSBAYDYEBRARDANIDRALEEYPNRSAONGDLTOSSIRALSLEXLUAIYELXPACIRTGOPHNICAVEYLBOLAONMMREDANAELDINEGEIBBRFEUATNINEGWLDYRDADINNGARTHEEHOOISNEOFTWHEUNDFERRLWAIZADOZFOCNDIALEESVADSNTEURDINNWODERNLA",6);
        /*Crossing x = new Crossing();

        Integer[] jed1 = {1,5,3,4,2};
        Integer[] jed2 = {3,1,5,4,2};
        Integer[] res = x.crossover(jed1,jed2,0.85);

        System.out.println(Arrays.toString(res));*/
    }
}
